### ISSUE TITLE
URL params does not match to documentation

### ISSUE THREAD

**Issue by aduponchel** [craftzing/akeneo-api#8]
Hi,

```javascript
import client from '@craftzing/akeneo-api';

const akeneo = client({
  baseURL,
  username,
  password,
  clientId,
  secret,
  // Optionally you can also pass in axiosOptions which will be passed to the Axios instance
});

console.log(await akeneo.productModel.getAll({}));
```
https://github.com/craftzing/node-akeneo-api/blob/1d73672359ea6db87238d2e9461000edeaf99735/src/http-client.ts#L30

It seems `baseURL` in documentation has to be `url`, or the other way around.  
Moreover you don't support trailing '/' on URL.
It could be a good improvement to support it or announce it in readme.

Thank you for making it open source :)

**Comment by jensdev** [comment]
Hi, thanks for your feedback. 
I've updated the README and updated the `http-client.ts`, it should now handle trailing slashes correctly. https://www.npmjs.com/package/@craftzing/akeneo-api
